# Generated by Django 3.2.5 on 2021-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_pass_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
